eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.43.212:1521/xe
    driverClassName: oracle.jdbc.OracleDriver
    username: system
    password: jithu
  jpa:
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: none
      
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
